version: '3'

services:
  app:
    build: .
    restart: always
    ports:
      - '8001:80'
    volumes:
      - '.:/var/www/html'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: yobasystems/alpine-mariadb:10.6.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "scout"
      MYSQL_PASSWORD: "scout"
      MYSQL_DATABASE: "scout"
    volumes:
      - './schema.sql:/docker-entrypoint-initdb.d/1.sql'
      - './insert-data-20220618.sql:/docker-entrypoint-initdb.d/2.sql'
      - 'mysql:/var/lib/mysql'
    healthcheck:
      # checks if db instance is accessible already
      test: out=$$(mysqladmin ping -h localhost -P 3306 -u root 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }
      interval: 2s
      timeout: 10s
      retries: 10

volumes:
  mysql: