-- MySQL Script generated by MySQL Workbench
-- Wed Jan 20 19:32:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema scout
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema scout
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scout` DEFAULT CHARACTER SET utf8 ;
USE `scout` ;

-- -----------------------------------------------------
-- Table `scout`.`reflexion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scout`.`reflexion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `goal_reached` DECIMAL(3,2) NULL,
  `volume_and_concentration` DECIMAL(3,2) NULL,
  `mood` DECIMAL(3,2) NULL,
  `program` DECIMAL(3,2) NULL,
  `average` DECIMAL(3,2) NULL,
  `comments` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
